name: nexah
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  flutter_svg: ^1.0.3
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.0.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  path_provider: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
